#!/bin/bash

if [ ! -f .gitcommit.amend.user ]; then
  echo `date` > .gitcommit.amend.user

  ./version.hook.sh
  git add Sshfs/Sshfs/Properties/AssemblyInfo.cs
  git commit --amend -C HEAD --no-verify

  rm .gitcommit.amend.user
fi 